// src/atoms/x-alert/x-alert.svelte
<script lang="ts">
import type { Snippet } from 'svelte';
import type { XAlertProps } from './types';
import { computeAlertClasses } from './x-alert.controller';

interface SvelteAlertProps extends XAlertProps {
  class?: string;
  onclose?: () => void;
  children?: Snippet;
  titleSnippet?: Snippet;
  icon?: Snippet;
}

let {
  type = 'info',
  title = undefined,
  text = undefined,
  closable = false,
  variant = undefined,
  class: className = '',
  onclose,
  children,
  titleSnippet,
  icon,
}: SvelteAlertProps = $props();

const alertClasses = $derived(
  computeAlertClasses({ type, variant }, className).join(' ')
);
</script>

<div class={alertClasses} role="alert">
  {#if icon}
    <div class="x-alert__icon">
      {@render icon()}
    </div>
  {/if}

  <div class="x-alert__content">
    {#if titleSnippet}
      <div class="x-alert__title">{@render titleSnippet()}</div>
    {:else if title}
      <div class="x-alert__title">{title}</div>
    {/if}

    {#if text}
      <div class="x-alert__text">{text}</div>
    {:else if children}
      <div class="x-alert__text">{@render children()}</div>
    {/if}
  </div>

  {#if closable}
    <button
      type="button"
      class="x-alert__close"
      onclick={onclose}
      aria-label="Close alert"
    >
      &times;
    </button>
  {/if}
</div>

// src/atoms/x-alert/x-alert.tsx
import React from 'react';
import type { XAlertProps } from './types';
import { computeAlertClasses } from './x-alert.controller';

export interface ReactAlertProps extends XAlertProps {
  className?: string;
  onClose?: () => void;
  children?: React.ReactNode;
  icon?: React.ReactNode;
}

export const XAlertReact: React.FC<ReactAlertProps> = ({
  type = 'info',
  title = undefined,
  text = undefined,
  closable = false,
  variant = undefined,
  className = '',
  onClose = undefined,
  children = null,
  icon = null,
}) => {
  const resolvedClassNames = computeAlertClasses(
    { type, variant },
    className
  ).join(' ');

  return (
    <div className={resolvedClassNames} role="alert">
      {icon ? <div className="x-alert__icon">{icon}</div> : null}

      <div className="x-alert__content">
        {title ? <div className="x-alert__title">{title}</div> : null}
        {text ? (
          <div className="x-alert__text">{text}</div>
        ) : (
          <div className="x-alert__text">{children}</div>
        )}
      </div>

      {closable ? (
        <button
          type="button"
          className="x-alert__close"
          onClick={onClose}
          aria-label="Close alert"
        >
          &times;
        </button>
      ) : null}
    </div>
  );
};

export default XAlertReact;
