// src/atoms/x-skeleton/x-skeleton.svelte
<script lang="ts">
import type { XSkeletonProps } from './types';
import { computeSkeletonClasses, formatDimension } from './x-skeleton.controller';

interface SvelteSkeletonProps extends XSkeletonProps {
  class?: string;
}

let {
  shape = 'rounded',
  animation = 'shimmer',
  width = '100%',
  height = '1rem',
  delay = '0s',
  class: className = '',
}: SvelteSkeletonProps = $props();

const skeletonClasses = $derived(
  computeSkeletonClasses({ shape, animation }, className).join(' ')
);
const resolvedWidth = $derived(formatDimension(width));
const resolvedHeight = $derived(formatDimension(height));
</script>

<div
  class={skeletonClasses}
  style:width={resolvedWidth}
  style:height={resolvedHeight}
  style:--x-skeleton-delay={delay}
></div>

<style lang="scss" src="./_x-skeleton.scss"></style>

// src/atoms/x-skeleton/x-skeleton.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { XSkeletonProps } from './types';
import { computeSkeletonClasses, formatDimension } from './x-skeleton.controller';

defineOptions({
  name: 'XSkeleton',
});

const props = withDefaults(defineProps<XSkeletonProps>(), {
  shape: 'rounded',
  animation: 'shimmer',
  width: '100%',
  height: '1rem',
  delay: '0s',
});

const classes = computed(() => computeSkeletonClasses(props));
const resolvedWidth = computed(() => formatDimension(props.width));
const resolvedHeight = computed(() => formatDimension(props.height));
</script>

<template>
  <div
    :class="classes"
    :style="{
      width: resolvedWidth,
      height: resolvedHeight,
      '--x-skeleton-delay': props.delay,
    }"
  />
</template>

<style lang="scss" src="./_x-skeleton.scss"></style>
