// src/atoms/x-switch/x-switch.tsx
import React from 'react';
import type { XSwitchProps } from './types';
import { computeSwitchClasses } from './x-switch.controller';

export interface ReactSwitchProps extends XSwitchProps {
  className?: string;
  onChange?: (val: boolean) => void;
  children?: React.ReactNode;
}

export const XSwitchReact: React.FC<ReactSwitchProps> = ({
  modelValue = false,
  label = undefined,
  disabled = false,
  className = '',
  onChange = undefined,
  children = null,
}) => {
  const resolvedClassNames = computeSwitchClasses(
    { disabled },
    modelValue,
    className
  ).join(' ');

  const handleToggle = () => {
    if (disabled) return;
    const nextVal = !modelValue;
    onChange?.(nextVal);
  };

  return (
    <div
      className={resolvedClassNames}
      onClick={handleToggle}
      onKeyDown={(e) => {
        if (e.key === ' ' || e.key === 'Enter') {
          e.preventDefault();
          handleToggle();
        }
      }}
      role="switch"
      aria-checked={modelValue}
      tabIndex={disabled ? -1 : 0}
    >
      <span className="x-switch__track">
        <span className="x-switch__thumb" />
      </span>

      {label ? <span className="x-switch__label">{label}</span> : children}
    </div>
  );
};

export default XSwitchReact;

// src/atoms/x-switch/x-switch.svelte
<script lang="ts">
import type { Snippet } from 'svelte';
import type { XSwitchProps } from './types';
import { computeSwitchClasses } from './x-switch.controller';

interface SvelteSwitchProps extends XSwitchProps {
  class?: string;
  onchange?: (val: boolean) => void;
  children?: Snippet;
}

let {
  modelValue = $bindable(false),
  label = undefined,
  disabled = false,
  class: className = '',
  onchange,
  children,
}: SvelteSwitchProps = $props();

const switchClasses = $derived(
  computeSwitchClasses({ disabled }, modelValue, className).join(' ')
);

const handleToggle = () => {
  if (disabled) return;
  modelValue = !modelValue;
  onchange?.(modelValue);
};
</script>

<div
  class={switchClasses}
  onclick={handleToggle}
  onkeydown={(e) => {
    if (e.key === ' ' || e.key === 'Enter') {
      e.preventDefault();
      handleToggle();
    }
  }}
  role="switch"
  aria-checked={modelValue}
  tabindex={disabled ? -1 : 0}
>
  <span class="x-switch__track">
    <span class="x-switch__thumb"></span>
  </span>

  {#if label}
    <span class="x-switch__label">{label}</span>
  {:else if children}
    {@render children()}
  {/if}
</div>
