// src/atoms/x-progress-linear/x-progress-linear.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue';
import type { XProgressLinearProps } from './types';
import { clampProgress } from './x-progress-linear.controller';

defineOptions({
  name: 'XProgressLinear',
  inheritAttrs: false,
});

const props = withDefaults(defineProps<XProgressLinearProps>(), {
  modelValue: 0,
  indeterminate: false,
  color: 'primary',
  height: 4,
  rounded: true,
  striped: false,
});

const attrs = useAttrs();
const progressValue = computed(() => clampProgress(props.modelValue));
</script>

<template>
  <v-progress-linear
    v-bind="attrs"
    :model-value="progressValue"
    :indeterminate="props.indeterminate"
    :color="props.color"
    :height="props.height"
    :rounded="props.rounded"
    :striped="props.striped"
    class="x-progress-linear"
  />
</template>

<style lang="scss" src="./_x-progress-linear.scss"></style>

// src/atoms/x-progress-linear/x-progress-linear.svelte
<script lang="ts">
import type { XProgressLinearProps } from './types';
import { clampProgress, computeProgressClasses } from './x-progress-linear.controller';

interface SvelteProgressLinearProps extends XProgressLinearProps {
  class?: string;
}

let {
  modelValue = 0,
  indeterminate = false,
  height = 4,
  rounded = true,
  striped = false,
  class: className = '',
}: SvelteProgressLinearProps = $props();

const progressValue = $derived(clampProgress(modelValue));
const progressClasses = $derived(
  computeProgressClasses({ indeterminate, rounded, striped }, className).join(' ')
);
const resolvedHeight = $derived(typeof height === 'number' ? `${height}px` : height);
</script>

<div
  class={progressClasses}
  style:height={resolvedHeight}
  role="progressbar"
  aria-valuenow={indeterminate ? undefined : progressValue}
  aria-valuemin={0}
  aria-valuemax={100}
>
  <div
    class="x-progress-linear__bar"
    style:width={indeterminate ? undefined : `${progressValue}%`}
  ></div>
</div>

<style lang="scss" src="./_x-progress-linear.scss"></style>
