// src/atoms/x-btn/x-btn.svelte
<script lang="ts">
import type { Snippet } from 'svelte';
import type { XBtnProps } from './types';
import { computeBtnClasses } from './x-btn.controller';

interface SvelteBtnProps extends XBtnProps {
  class?: string;
  onclick?: (e: MouseEvent) => void;
  children?: Snippet;
  prepend?: Snippet;
  append?: Snippet;
}

let {
  variant = undefined,
  color = undefined,
  size = 'default',
  block = false,
  loading = false,
  disabled = false,
  icon = false,
  class: className = '',
  onclick,
  children,
  prepend,
  append,
}: SvelteBtnProps = $props();

const btnClasses = $derived(
  computeBtnClasses(
    { variant, size, block, loading, disabled, icon, color },
    className
  ).join(' ')
);
</script>

<button
  type="button"
  class={btnClasses}
  disabled={disabled || loading}
  {onclick}
>
  {#if prepend}
    <span class="x-btn__prepend">
      {@render prepend()}
    </span>
  {/if}

  {#if children}
    <span class="x-btn__content">
      {@render children()}
    </span>
  {/if}

  {#if append}
    <span class="x-btn__append">
      {@render append()}
    </span>
  {/if}
</button>

// src/atoms/x-btn/x-btn.tsx
import React from 'react';
import type { XBtnProps } from './types';
import { computeBtnClasses } from './x-btn.controller';

export interface ReactBtnProps extends XBtnProps {
  className?: string;
  onClick?: (e: React.MouseEvent<HTMLButtonElement>) => void;
  children?: React.ReactNode;
  prepend?: React.ReactNode;
  append?: React.ReactNode;
}

export const XBtnReact: React.FC<ReactBtnProps> = ({
  variant = undefined,
  color = undefined,
  size = 'default',
  block = false,
  loading = false,
  disabled = false,
  icon = false,
  className = '',
  onClick = undefined,
  children = null,
  prepend = null,
  append = null,
}) => {
  const isButtonDisabled = disabled || loading;
  const resolvedClassNames = computeBtnClasses(
    { variant, color, size, block, loading, disabled, icon },
    className
  ).join(' ');

  return (
    <button
      type="button"
      className={resolvedClassNames}
      disabled={isButtonDisabled}
      onClick={onClick}
    >
      {prepend ? <span className="x-btn__prepend">{prepend}</span> : null}
      {children ? <span className="x-btn__content">{children}</span> : null}
      {append ? <span className="x-btn__append">{append}</span> : null}
    </button>
  );
};

export default XBtnReact;
