// src/atoms/x-btn/x-btn.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue';
import type { XBtnProps, XBtnVariant } from './types';

defineOptions({
  name: 'XBtn',
  inheritAttrs: false,
});

const props = withDefaults(defineProps<XBtnProps>(), {
  variant: 'elevated',
  color: undefined,
  size: 'default',
  block: false,
  loading: false,
  disabled: false,
  icon: false,
});

const attrs = useAttrs();

const isGlassVariant = computed(() => props.variant === 'glass');

const computedVuetifyVariant = computed(() => {
  if (isGlassVariant.value) {
    return 'flat';
  }
  return props.variant as Exclude<XBtnVariant, 'glass'>;
});

const resolvedColor = computed(() => {
  if (isGlassVariant.value && !props.color) {
    return undefined;
  }
  return props.color;
});
</script>

<template>
  <v-btn
    v-bind="attrs"
    :variant="computedVuetifyVariant"
    :color="resolvedColor"
    :size="props.size"
    :block="props.block"
    :loading="props.loading"
    :disabled="props.disabled"
    :icon="props.icon"
    :class="['x-btn', { 'x-btn--glass': isGlassVariant }]"
  >
    <template v-if="$slots.prepend" #prepend>
      <slot name="prepend" />
    </template>
    <template v-if="$slots.append" #append>
      <slot name="append" />
    </template>
    <template v-if="$slots.loader" #loader>
      <slot name="loader" />
    </template>
    <template #default>
      <slot />
    </template>
  </v-btn>
</template>

<style lang="scss" src="./_x-btn.scss"></style>

// src/atoms/x-btn/x-btn.svelte
<script lang="ts">
import type { Snippet } from 'svelte';
import type { XBtnProps } from './types';
import { computeBtnClasses } from './x-btn.controller';

interface SvelteBtnProps extends XBtnProps {
  class?: string;
  onclick?: (e: MouseEvent) => void;
  children?: Snippet;
  prepend?: Snippet;
  append?: Snippet;
}

let {
  variant = 'glass',
  color = undefined,
  size = 'default',
  block = false,
  loading = false,
  disabled = false,
  icon = false,
  class: className = '',
  onclick,
  children,
  prepend,
  append,
}: SvelteBtnProps = $props();

const btnClasses = $derived(
  computeBtnClasses(
    { variant, size, block, loading, disabled, icon, color },
    className
  ).join(' ')
);
</script>

<button
  type="button"
  class={btnClasses}
  disabled={disabled || loading}
  {onclick}
>
  {#if prepend}
    <span class="x-btn__prepend">
      {@render prepend()}
    </span>
  {/if}

  {#if children}
    <span class="x-btn__content">
      {@render children()}
    </span>
  {/if}

  {#if append}
    <span class="x-btn__append">
      {@render append()}
    </span>
  {/if}
</button>

<style lang="scss" src="./_x-btn.scss"></style>
