// src/molecules/m-toast/m-toast.svelte
<script lang="ts">
import type { MToastProps } from './types';
import { computeToastClasses } from './m-toast.controller';
import XBtn from '../../atoms/x-btn/x-btn.svelte';

interface SvelteToastProps extends MToastProps {
  class?: string;
  onclickaction?: () => void;
  onclose?: () => void;
}

let {
  modelValue = $bindable(false),
  message,
  type = 'info',
  duration = 4000,
  actionText = undefined,
  class: className = '',
  onclickaction,
  onclose,
}: SvelteToastProps = $props();

let timerId: any = null;

$effect(() => {
  if (timerId) clearTimeout(timerId);
  if (modelValue && duration > 0) {
    timerId = setTimeout(() => {
      modelValue = false;
      onclose?.();
    }, duration);
  }
  return () => {
    if (timerId) clearTimeout(timerId);
  };
});

const toastClasses = $derived(
  computeToastClasses({ message, type }, modelValue, className).join(' ')
);
</script>

<div class={toastClasses} role="status">
  <span class="m-toast__message">{message}</span>

  <div class="m-toast__actions">
    {#if actionText}
      <XBtn variant="text" size="small" onclick={onclickaction}>
        {#snippet children()}{actionText}{/snippet}
      </XBtn>
    {/if}

    <XBtn variant="plain" size="x-small" icon={true} onclick={() => {
      modelValue = false;
      onclose?.();
    }}>
      {#snippet children()}&times;{/snippet}
    </XBtn>
  </div>
</div>

<style lang="scss" src="./_m-toast.scss"></style>

// src/molecules/m-toast/m-toast.tsx
import React, { useEffect, useRef } from 'react';
import type { MToastProps } from './types';
import { computeToastClasses } from './m-toast.controller';
import XBtnReact from '../../atoms/x-btn/x-btn';

export interface ReactToastProps extends MToastProps {
  className?: string;
  onClickAction?: () => void;
  onClose?: () => void;
}

export const MToastReact: React.FC<ReactToastProps> = ({
  modelValue = false,
  message,
  type = 'info',
  duration = 4000,
  actionText = undefined,
  className = '',
  onClickAction = undefined,
  onClose = undefined,
}) => {
  const timerRef = useRef<any>(null);

  useEffect(() => {
    if (timerRef.current) clearTimeout(timerRef.current);
    if (modelValue && duration > 0) {
      timerRef.current = setTimeout(() => {
        onClose?.();
      }, duration);
    }
    return () => {
      if (timerRef.current) clearTimeout(timerRef.current);
    };
  }, [modelValue, duration, onClose]);

  const resolvedClassNames = computeToastClasses(
    { message, type },
    modelValue,
    className
  ).join(' ');

  return (
    <div className={resolvedClassNames} role="status">
      <span className="m-toast__message">{message}</span>

      <div className="m-toast__actions">
        {actionText ? (
          <XBtnReact
            variant="text"
            size="small"
            color="primary"
            onClick={onClickAction}
          >
            {actionText}
          </XBtnReact>
        ) : null}

        <XBtnReact
          variant="plain"
          size="x-small"
          icon={true}
          onClick={onClose}
        >
          &times;
        </XBtnReact>
      </div>
    </div>
  );
};

export default MToastReact;
