// src/atoms/x-dialog/x-dialog.svelte
<script lang="ts">
import type { Snippet } from 'svelte';
import type { XDialogProps } from './types';
import { computeDialogClasses, computeDialogSurfaceVars, shouldDismissDialog } from './x-dialog.controller';
import { listen, toStyleString } from '../../core';

interface SvelteDialogProps extends XDialogProps {
  class?: string;
  title?: Snippet;
  actions?: Snippet;
  children?: Snippet;
}

let {
  modelValue = $bindable(false),
  maxWidth = 600,
  width = undefined,
  persistent = false,
  scrollable = false,
  fullscreen = false,
  class: className = '',
  title,
  actions,
  children,
}: SvelteDialogProps = $props();

const dialogClasses = $derived(computeDialogClasses({ fullscreen, scrollable }, `x-dialog--native ${className}`.trim()).join(' '));
const surfaceStyle = $derived(toStyleString(computeDialogSurfaceVars({ maxWidth, width })));

const requestClose = () => {
  const isDismissible = shouldDismissDialog({ persistent });
  if (isDismissible) modelValue = false;
};

$effect(() => {
  if (!modelValue) return undefined;
  return listen(globalThis.document, 'keydown', (event) => {
    const isEscape = (event as KeyboardEvent).key === 'Escape';
    if (isEscape) requestClose();
  });
});
</script>

{#if modelValue}
  <div class={dialogClasses} role="presentation" onclick={requestClose}>
    <div
      class="x-dialog__surface"
      role="dialog"
      aria-modal="true"
      tabindex="-1"
      style={surfaceStyle}
      onclick={(event) => event.stopPropagation()}
    >
      {#if title}
        <div class="x-dialog__title">{@render title()}</div>
      {/if}
      <div class="x-dialog__content">
        {@render children?.()}
      </div>
      {#if actions}
        <div class="x-dialog__actions">{@render actions()}</div>
      {/if}
    </div>
  </div>
{/if}

// src/atoms/x-dialog/x-dialog.tsx
import React, { useEffect } from 'react';
import type { XDialogProps } from './types';
import { computeDialogClasses, computeDialogSurfaceVars, shouldDismissDialog } from './x-dialog.controller';
import { listen } from '../../core';

export interface ReactDialogProps extends XDialogProps {
  className?: string;
  onUpdateModelValue?: (value: boolean) => void;
  title?: React.ReactNode;
  actions?: React.ReactNode;
  children?: React.ReactNode;
}

export const XDialogReact: React.FC<ReactDialogProps> = ({
  modelValue = false,
  maxWidth = 600,
  width = undefined,
  persistent = false,
  scrollable = false,
  fullscreen = false,
  className = '',
  onUpdateModelValue = undefined,
  title = null,
  actions = null,
  children = null,
}) => {
  const isDismissible = shouldDismissDialog({ persistent });
  const requestClose = () => {
    if (isDismissible) onUpdateModelValue?.(false);
  };

  useEffect(() => {
    if (!modelValue) return undefined;
    return listen(globalThis.document, 'keydown', (event) => {
      const isEscape = (event as KeyboardEvent).key === 'Escape';
      if (isEscape) requestClose();
    });
  });

  if (!modelValue) return null;

  const resolvedClassNames = computeDialogClasses({ fullscreen, scrollable }, `x-dialog--native ${className}`.trim()).join(' ');
  const surfaceVars = computeDialogSurfaceVars({ maxWidth, width }) as React.CSSProperties;

  return (
    <div className={resolvedClassNames} role="presentation" onClick={requestClose}>
      <div
        className="x-dialog__surface"
        role="dialog"
        aria-modal="true"
        style={surfaceVars}
        onClick={(event) => event.stopPropagation()}
      >
        {title ? <div className="x-dialog__title">{title}</div> : null}
        <div className="x-dialog__content">{children}</div>
        {actions ? <div className="x-dialog__actions">{actions}</div> : null}
      </div>
    </div>
  );
};

export default XDialogReact;
