// src/atoms/x-grid/x-grid.tsx
import React from 'react';
import type { XGridProps } from './types';
import { computeGridClasses, computeGridVars } from './x-grid.controller';

export interface ReactGridProps extends XGridProps {
  className?: string;
  children?: React.ReactNode;
}

export const XGridReact: React.FC<ReactGridProps> = ({
  columns = 1,
  minItemWidth = undefined,
  gap = 'md',
  align = undefined,
  tag: Element = 'div',
  className = '',
  children = null,
}) => {
  const resolvedClassNames = computeGridClasses({ columns, minItemWidth, gap, align }, className).join(' ');
  const gridVars = computeGridVars({ minItemWidth }) as React.CSSProperties;
  return <Element className={resolvedClassNames} style={gridVars}>{children}</Element>;
};

export default XGridReact;

// src/atoms/x-grid/x-grid.svelte
<script lang="ts">
import type { Snippet } from 'svelte';
import type { XGridProps } from './types';
import { computeGridClasses, computeGridVars } from './x-grid.controller';
import { toStyleString } from '../../core';

interface SvelteGridProps extends XGridProps {
  class?: string;
  children?: Snippet;
}

let {
  columns = 1,
  minItemWidth = undefined,
  gap = 'md',
  align = undefined,
  tag = 'div',
  class: className = '',
  children,
}: SvelteGridProps = $props();

const gridClasses = $derived(computeGridClasses({ columns, minItemWidth, gap, align }, className).join(' '));
const gridStyle = $derived(toStyleString(computeGridVars({ minItemWidth })));
</script>

<svelte:element this={tag} class={gridClasses} style={gridStyle}>
  {@render children?.()}
</svelte:element>

<style lang="scss" src="./_x-grid.scss"></style>
