// src/atoms/x-stack/x-stack.tsx
import React from 'react';
import type { XStackProps } from './types';
import { computeStackClasses } from './x-stack.controller';

export interface ReactStackProps extends XStackProps {
  className?: string;
  children?: React.ReactNode;
}

export const XStackReact: React.FC<ReactStackProps> = ({
  direction = 'column',
  gap = 'md',
  align = undefined,
  justify = undefined,
  wrap = false,
  tag: Element = 'div',
  className = '',
  children = null,
}) => {
  const resolvedClassNames = computeStackClasses({ direction, gap, align, justify, wrap }, className).join(' ');
  return <Element className={resolvedClassNames}>{children}</Element>;
};

export default XStackReact;

// src/atoms/x-stack/x-stack.svelte
<script lang="ts">
import type { Snippet } from 'svelte';
import type { XStackProps } from './types';
import { computeStackClasses } from './x-stack.controller';

interface SvelteStackProps extends XStackProps {
  class?: string;
  children?: Snippet;
}

let {
  direction = 'column',
  gap = 'md',
  align = undefined,
  justify = undefined,
  wrap = false,
  tag = 'div',
  class: className = '',
  children,
}: SvelteStackProps = $props();

const stackClasses = $derived(computeStackClasses({ direction, gap, align, justify, wrap }, className).join(' '));
</script>

<svelte:element this={tag} class={stackClasses}>
  {@render children?.()}
</svelte:element>

<style lang="scss" src="./_x-stack.scss"></style>
