// src/atoms/x-badge/x-badge.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue';
import type { XBadgeProps } from './types';
import { resolveBadgeDisplay } from './x-badge.controller';

defineOptions({
  name: 'XBadge',
  inheritAttrs: false,
});

const props = withDefaults(defineProps<XBadgeProps>(), {
  content: undefined,
  color: 'primary',
  dot: false,
  inline: false,
  max: 99,
  floating: true,
});

const attrs = useAttrs();

const displayText = computed(() => resolveBadgeDisplay(props.content, props.max));
const hasSlotContent = computed(() => Boolean(attrs.default));
</script>

<template>
  <v-badge
    v-bind="attrs"
    :content="displayText"
    :color="props.color"
    :dot="props.dot"
    :inline="props.inline"
    :max="props.max"
    :floating="props.floating"
    class="x-badge"
  >
    <slot />
  </v-badge>
</template>

<style lang="scss" src="./_x-badge.scss"></style>

// src/atoms/x-badge/x-badge.svelte
<script lang="ts">
import type { Snippet } from 'svelte';
import type { XBadgeProps } from './types';
import { resolveBadgeDisplay, computeBadgeClasses } from './x-badge.controller';

interface SvelteBadgeProps extends XBadgeProps {
  class?: string;
  children?: Snippet;
}

let {
  content = undefined,
  color = 'primary',
  dot = false,
  inline = false,
  max = 99,
  floating = true,
  class: className = '',
  children,
}: SvelteBadgeProps = $props();

const displayText = $derived(resolveBadgeDisplay(content, max));
const badgeClasses = $derived(
  computeBadgeClasses({ dot, inline, floating, color }, className).join(' ')
);
</script>

{#if children}
  <div class="x-badge-wrapper">
    {@render children()}
    <span class={badgeClasses}>
      {#if !dot}
        {displayText}
      {/if}
    </span>
  </div>
{:else}
  <span class={badgeClasses}>
    {#if !dot}
      {displayText}
    {/if}
  </span>
{/if}

<style lang="scss" src="./_x-badge.scss"></style>
