// src/atoms/x-badge/x-badge.tsx
import React from 'react';
import type { XBadgeProps } from './types';
import { resolveBadgeDisplay, computeBadgeClasses } from './x-badge.controller';

export interface ReactBadgeProps extends XBadgeProps {
  className?: string;
  children?: React.ReactNode;
}

export const XBadgeReact: React.FC<ReactBadgeProps> = ({
  content = undefined,
  color = 'primary',
  dot = false,
  inline = false,
  max = 99,
  floating = true,
  className = '',
  children = null,
}) => {
  const displayText = resolveBadgeDisplay(content, max);
  const resolvedClassNames = computeBadgeClasses(
    { dot, inline, floating, color },
    className
  ).join(' ');

  if (children) {
    return (
      <div className="x-badge-wrapper">
        {children}
        <span className={resolvedClassNames}>{!dot ? displayText : null}</span>
      </div>
    );
  }

  return <span className={resolvedClassNames}>{!dot ? displayText : null}</span>;
};

export default XBadgeReact;

// src/atoms/x-badge/x-badge.svelte
<script lang="ts">
import type { Snippet } from 'svelte';
import type { XBadgeProps } from './types';
import { resolveBadgeDisplay, computeBadgeClasses } from './x-badge.controller';

interface SvelteBadgeProps extends XBadgeProps {
  class?: string;
  children?: Snippet;
}

let {
  content = undefined,
  color = 'primary',
  dot = false,
  inline = false,
  max = 99,
  floating = true,
  class: className = '',
  children,
}: SvelteBadgeProps = $props();

const displayText = $derived(resolveBadgeDisplay(content, max));
const badgeClasses = $derived(
  computeBadgeClasses({ dot, inline, floating, color }, className).join(' ')
);
</script>

{#if children}
  <div class="x-badge-wrapper">
    {@render children()}
    <span class={badgeClasses}>
      {#if !dot}
        {displayText}
      {/if}
    </span>
  </div>
{:else}
  <span class={badgeClasses}>
    {#if !dot}
      {displayText}
    {/if}
  </span>
{/if}
