// src/atoms/x-list/x-list.tsx
import React from 'react';
import type { XListProps } from './types';
import { computeListClasses } from './x-list.controller';

export interface ReactListProps extends XListProps {
  className?: string;
  children?: React.ReactNode;
}

export const XListReact: React.FC<ReactListProps> = ({
  density = 'default',
  lines = 'one',
  nav = false,
  color = undefined,
  variant = undefined,
  disabled = false,
  className = '',
  children = null,
}) => {
  const resolvedClassNames = computeListClasses(
    { density, lines, nav, color, variant, disabled },
    className
  ).join(' ');

  return <div className={resolvedClassNames}>{children}</div>;
};

export default XListReact;

// src/atoms/x-list/x-list.svelte
<script lang="ts">
import type { Snippet } from 'svelte';
import type { XListProps } from './types';
import { computeListClasses } from './x-list.controller';

interface SvelteListProps extends XListProps {
  class?: string;
  children?: Snippet;
}

let {
  density = 'default',
  lines = 'one',
  nav = false,
  color = undefined,
  variant = undefined,
  disabled = false,
  class: className = '',
  children,
}: SvelteListProps = $props();

const listClasses = $derived(
  computeListClasses({ density, lines, nav, color, variant, disabled }, className).join(' ')
);
</script>

<div class={listClasses}>
  {#if children}
    {@render children()}
  {/if}
</div>
