// src/atoms/x-text/x-text.tsx
import React from 'react';
import type { XTextProps } from './types';
import { computeTextClasses, resolveTextTag } from './x-text.controller';

export interface ReactTextProps extends XTextProps {
  className?: string;
  children?: React.ReactNode;
}

export const XTextReact: React.FC<ReactTextProps> = ({
  tag = undefined,
  variant = 'body',
  tone = undefined,
  weight = undefined,
  align = undefined,
  truncate = false,
  className = '',
  children = null,
}) => {
  const Element = resolveTextTag({ tag, variant });
  const resolvedClassNames = computeTextClasses({ variant, tone, weight, align, truncate }, className).join(' ');
  return <Element className={resolvedClassNames}>{children}</Element>;
};

export default XTextReact;

// src/atoms/x-text/x-text.svelte
<script lang="ts">
import type { Snippet } from 'svelte';
import type { XTextProps } from './types';
import { computeTextClasses, resolveTextTag } from './x-text.controller';

interface SvelteTextProps extends XTextProps {
  class?: string;
  children?: Snippet;
}

let {
  tag = undefined,
  variant = 'body',
  tone = undefined,
  weight = undefined,
  align = undefined,
  truncate = false,
  class: className = '',
  children,
}: SvelteTextProps = $props();

const element = $derived(resolveTextTag({ tag, variant }));
const textClasses = $derived(computeTextClasses({ variant, tone, weight, align, truncate }, className).join(' '));
</script>

<svelte:element this={element} class={textClasses}>
  {@render children?.()}
</svelte:element>

<style lang="scss" src="./_x-text.scss"></style>
