// src/molecules/m-empty-state/m-empty-state.tsx
import React from 'react';
import type { MEmptyStateProps } from './types';
import XCardReact from '../../atoms/x-card/x-card';
import XBtnReact from '../../atoms/x-btn/x-btn';

export interface ReactEmptyStateProps extends MEmptyStateProps {
  className?: string;
  onClickAction?: () => void;
  iconElement?: React.ReactNode;
  actionElement?: React.ReactNode;
}

export const MEmptyStateReact: React.FC<ReactEmptyStateProps> = ({
  title,
  description = undefined,
  icon = '✨',
  actionText = undefined,
  className = '',
  onClickAction = undefined,
  iconElement = null,
  actionElement = null,
}) => {
  return (
    <XCardReact variant="glass" className={`m-empty-state ${className}`}>
      <div className="m-empty-state__icon-wrap">
        {iconElement ? iconElement : <span>{icon}</span>}
      </div>

      <h3 className="m-empty-state__title">{title}</h3>

      {description ? (
        <p className="m-empty-state__description">{description}</p>
      ) : null}

      {actionElement ? (
        <div className="m-empty-state__actions">{actionElement}</div>
      ) : actionText ? (
        <div className="m-empty-state__actions">
          <XBtnReact variant="elevated" color="primary" onClick={onClickAction}>
            {actionText}
          </XBtnReact>
        </div>
      ) : null}
    </XCardReact>
  );
};

export default MEmptyStateReact;

// src/molecules/m-empty-state/m-empty-state.svelte
<script lang="ts">
import type { Snippet } from 'svelte';
import type { MEmptyStateProps } from './types';
import XCard from '../../atoms/x-card/x-card.svelte';
import XBtn from '../../atoms/x-btn/x-btn.svelte';

interface SvelteEmptyStateProps extends MEmptyStateProps {
  onclickaction?: () => void;
  iconSnippet?: Snippet;
  actionSnippet?: Snippet;
}

let {
  title,
  description = undefined,
  icon = '✨',
  actionText = undefined,
  onclickaction,
  iconSnippet,
  actionSnippet,
}: SvelteEmptyStateProps = $props();
</script>

<XCard variant="glass" class="m-empty-state">
  {#snippet children()}
    <div class="m-empty-state__icon-wrap">
      {#if iconSnippet}
        {@render iconSnippet()}
      {:else}
        <span>{icon}</span>
      {/if}
    </div>

    <h3 class="m-empty-state__title">{title}</h3>

    {#if description}
      <p class="m-empty-state__description">{description}</p>
    {/if}

    {#if actionSnippet}
      <div class="m-empty-state__actions">
        {@render actionSnippet()}
      </div>
    {:else if actionText}
      <div class="m-empty-state__actions">
        <XBtn variant="elevated" color="primary" onclick={onclickaction}>
          {#snippet children()}{actionText}{/snippet}
        </XBtn>
      </div>
    {/if}
  {/snippet}
</XCard>

<style lang="scss" src="./_m-empty-state.scss"></style>
