// src/molecules/m-search-input/m-search-input.svelte
<script lang="ts">
import type { MSearchInputProps } from './types';
import { createDebounce, computeSearchInputClasses } from './m-search-input.controller';
import XTextField from '../../atoms/x-text-field/x-text-field.svelte';

interface SvelteSearchInputProps extends MSearchInputProps {
  class?: string;
  onsearch?: (val: string) => void;
  onclear?: () => void;
}

let {
  modelValue = $bindable(''),
  placeholder = 'Search...',
  debounceMs = 250,
  disabled = false,
  clearable = true,
  class: className = '',
  onsearch,
  onclear,
}: SvelteSearchInputProps = $props();

const emitSearchDebounced = createDebounce((val: string) => {
  onsearch?.(val);
}, debounceMs);

const handleInput = (e: Event) => {
  const target = e.target as HTMLInputElement;
  modelValue = target.value;
  emitSearchDebounced(target.value);
};

const handleClear = () => {
  modelValue = '';
  onclear?.();
  onsearch?.('');
};
</script>

<div class={computeSearchInputClasses({ disabled }, className).join(' ')}>
  <XTextField
    bind:modelValue
    {placeholder}
    {disabled}
    {clearable}
    oninput={handleInput}
    onclear={handleClear}
  >
    {#snippet prependInner()}
      <span class="m-search-input__icon">🔍</span>
    {/snippet}
  </XTextField>
</div>

<style lang="scss" src="./_m-search-input.scss"></style>

// src/molecules/m-search-input/m-search-input.tsx
import React, { useState, useEffect } from 'react';
import { useDebouncedCallback } from '../../adapters/react/useDebouncedCallback';
import type { MSearchInputProps } from './types';
import { computeSearchInputClasses } from './m-search-input.controller';
import XTextFieldReact from '../../atoms/x-text-field/x-text-field';

export interface ReactSearchInputProps extends MSearchInputProps {
  className?: string;
  onSearch?: (val: string) => void;
  onClear?: () => void;
}

export const MSearchInputReact: React.FC<ReactSearchInputProps> = ({
  modelValue = '',
  placeholder = 'Search...',
  debounceMs = 250,
  disabled = false,
  clearable = true,
  className = '',
  onSearch = undefined,
  onClear = undefined,
}) => {
  const [internalVal, setInternalVal] = useState(modelValue);
  const searchDebounced = useDebouncedCallback((val: string) => onSearch?.(val), debounceMs);

  useEffect(() => {
    setInternalVal(modelValue);
  }, [modelValue]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const val = e.target.value;
    setInternalVal(val);
    searchDebounced(val);
  };

  const handleClear = () => {
    setInternalVal('');
    onClear?.();
    onSearch?.('');
  };

  const resolvedClassNames = computeSearchInputClasses(
    { disabled },
    className
  ).join(' ');

  return (
    <div className={resolvedClassNames}>
      <XTextFieldReact
        modelValue={internalVal}
        placeholder={placeholder}
        disabled={disabled}
        clearable={clearable}
        onChange={handleChange}
        onClear={handleClear}
        prependInner={<span className="m-search-input__icon">🔍</span>}
      />
    </div>
  );
};

export default MSearchInputReact;
