// src/atoms/x-tooltip/x-tooltip.tsx
import React from 'react';
import type { XTooltipProps } from './types';
import { computeTooltipClasses } from './x-tooltip.controller';

export interface ReactTooltipProps extends XTooltipProps {
  className?: string;
  children: React.ReactNode;
  tooltip?: React.ReactNode;
}

export const XTooltipReact: React.FC<ReactTooltipProps> = ({
  text = undefined,
  location = 'top',
  disabled = false,
  className = '',
  children,
  tooltip = null,
}) => {
  if (disabled) {
    return <>{children}</>;
  }

  const resolvedClassNames = computeTooltipClasses(
    { location },
    className
  ).join(' ');

  return (
    // Visibility comes from .x-tooltip-wrapper:hover / :focus-within in glass-theme.
    <div className="x-tooltip-wrapper">
      {children}
      <div
        className={resolvedClassNames}
        role="tooltip"
      >
        {tooltip || text}
      </div>
    </div>
  );
};

export default XTooltipReact;

// src/atoms/x-tooltip/x-tooltip.svelte
<script lang="ts">
import type { Snippet } from 'svelte';
import type { XTooltipProps } from './types';
import { computeTooltipClasses } from './x-tooltip.controller';

interface SvelteTooltipProps extends XTooltipProps {
  class?: string;
  children?: Snippet;
  tooltip?: Snippet;
}

let {
  text = undefined,
  location = 'top',
  disabled = false,
  class: className = '',
  children,
  tooltip,
}: SvelteTooltipProps = $props();

const tooltipClasses = $derived(
  computeTooltipClasses({ location }, className).join(' ')
);
</script>

{#if disabled}
  {#if children}
    {@render children()}
  {/if}
{:else}
  <div class="x-tooltip-wrapper">
    {#if children}
      {@render children()}
    {/if}

    <div class={tooltipClasses} role="tooltip">
      {#if tooltip}
        {@render tooltip()}
      {:else}
        {text}
      {/if}
    </div>
  </div>
{/if}
