// src/atoms/x-avatar/x-avatar.tsx
import React from 'react';
import type { XAvatarProps } from './types';
import { computeAvatarClasses, getInitials } from './x-avatar.controller';

export interface ReactAvatarProps extends XAvatarProps {
  className?: string;
  children?: React.ReactNode;
}

export const XAvatarReact: React.FC<ReactAvatarProps> = ({
  src = undefined,
  alt = undefined,
  text = undefined,
  size = 'default',
  bordered = false,
  status = undefined,
  className = '',
  children = null,
}) => {
  const resolvedClassNames = computeAvatarClasses(
    { size, bordered, status },
    className
  ).join(' ');

  const initials = getInitials(text || alt);

  return (
    <div className={resolvedClassNames}>
      {src ? (
        <img src={src} alt={alt || 'Avatar'} />
      ) : initials ? (
        <span>{initials}</span>
      ) : (
        children
      )}

      {status ? (
        <span className={`x-avatar__status-dot x-avatar__status-dot--${status}`} />
      ) : null}
    </div>
  );
};

export default XAvatarReact;

// src/atoms/x-avatar/x-avatar.svelte
<script lang="ts">
import type { Snippet } from 'svelte';
import type { XAvatarProps } from './types';
import { computeAvatarClasses, getInitials } from './x-avatar.controller';

interface SvelteAvatarProps extends XAvatarProps {
  class?: string;
  children?: Snippet;
}

let {
  src = undefined,
  alt = undefined,
  text = undefined,
  size = 'default',
  bordered = false,
  status = undefined,
  class: className = '',
  children,
}: SvelteAvatarProps = $props();

const avatarClasses = $derived(
  computeAvatarClasses({ size, bordered, status }, className).join(' ')
);
const initials = $derived(getInitials(text || alt));
</script>

<div class={avatarClasses}>
  {#if src}
    <img {src} alt={alt || 'Avatar'} />
  {:else if initials}
    <span>{initials}</span>
  {:else if children}
    {@render children()}
  {/if}

  {#if status}
    <span class={['x-avatar__status-dot', `x-avatar__status-dot--${status}`].join(' ')}></span>
  {/if}
</div>
