// src/molecules/m-action-bar/m-action-bar.svelte
<script lang="ts">
import type { Snippet } from 'svelte';
import type { MActionBarProps } from './types';
import { computeActionBarClasses } from './m-action-bar.controller';
import XSheet from '../../atoms/x-sheet/x-sheet.svelte';

interface SvelteActionBarProps extends MActionBarProps {
  class?: string;
  start?: Snippet;
  children?: Snippet;
  end?: Snippet;
}

let {
  title = undefined,
  position = 'static',
  bordered = true,
  class: className = '',
  start,
  children,
  end,
}: SvelteActionBarProps = $props();

const barClasses = $derived(
  computeActionBarClasses({ position, bordered }, className).join(' ')
);
</script>

<XSheet class={barClasses}>
  {#snippet children()}
    <div class="m-action-bar__start">
      {#if start}
        {@render start()}
      {:else if title}
        <h2 class="m-action-bar__title">{title}</h2>
      {/if}
    </div>

    {#if children}
      <div class="m-action-bar__center">
        {@render children()}
      </div>
    {/if}

    {#if end}
      <div class="m-action-bar__end">
        {@render end()}
      </div>
    {/if}
  {/snippet}
</XSheet>

<style lang="scss" src="./_m-action-bar.scss"></style>

// src/molecules/m-action-bar/m-action-bar.tsx
import React from 'react';
import type { MActionBarProps } from './types';
import { computeActionBarClasses } from './m-action-bar.controller';
import XSheetReact from '../../atoms/x-sheet/x-sheet';

export interface ReactActionBarProps extends MActionBarProps {
  className?: string;
  start?: React.ReactNode;
  children?: React.ReactNode;
  end?: React.ReactNode;
}

export const MActionBarReact: React.FC<ReactActionBarProps> = ({
  title = undefined,
  position = 'static',
  bordered = true,
  className = '',
  start = null,
  children = null,
  end = null,
}) => {
  const resolvedClassNames = computeActionBarClasses(
    { position, bordered },
    className
  ).join(' ');

  return (
    <XSheetReact className={resolvedClassNames}>
      <div className="m-action-bar__start">
        {start ? (
          start
        ) : title ? (
          <h2 className="m-action-bar__title">{title}</h2>
        ) : null}
      </div>

      {children ? <div className="m-action-bar__center">{children}</div> : null}

      {end ? <div className="m-action-bar__end">{end}</div> : null}
    </XSheetReact>
  );
};

export default MActionBarReact;
