// src/molecules/m-action-bar/m-action-bar.vue
<script setup lang="ts">
import type { MActionBarProps } from './types';
import { computeActionBarClasses } from './m-action-bar.controller';
import XSheet from '../../atoms/x-sheet/x-sheet.vue';

defineOptions({
  name: 'MActionBar',
});

const props = withDefaults(defineProps<MActionBarProps>(), {
  title: undefined,
  position: 'static',
  bordered: true,
});
</script>

<template>
  <XSheet :class="computeActionBarClasses(props)">
    <div class="m-action-bar__start">
      <slot name="start">
        <h2 v-if="props.title" class="m-action-bar__title">{{ props.title }}</h2>
      </slot>
    </div>

    <div v-if="$slots.default" class="m-action-bar__center">
      <slot />
    </div>

    <div v-if="$slots.end" class="m-action-bar__end">
      <slot name="end" />
    </div>
  </XSheet>
</template>

<style lang="scss" src="./_m-action-bar.scss"></style>

// src/molecules/m-action-bar/m-action-bar.svelte
<script lang="ts">
import type { Snippet } from 'svelte';
import type { MActionBarProps } from './types';
import { computeActionBarClasses } from './m-action-bar.controller';
import XSheet from '../../atoms/x-sheet/x-sheet.svelte';

interface SvelteActionBarProps extends MActionBarProps {
  class?: string;
  start?: Snippet;
  children?: Snippet;
  end?: Snippet;
}

let {
  title = undefined,
  position = 'static',
  bordered = true,
  class: className = '',
  start,
  children,
  end,
}: SvelteActionBarProps = $props();

const barClasses = $derived(
  computeActionBarClasses({ position, bordered }, className).join(' ')
);
</script>

<XSheet class={barClasses}>
  {#snippet children()}
    <div class="m-action-bar__start">
      {#if start}
        {@render start()}
      {:else if title}
        <h2 class="m-action-bar__title">{title}</h2>
      {/if}
    </div>

    {#if children}
      <div class="m-action-bar__center">
        {@render children()}
      </div>
    {/if}

    {#if end}
      <div class="m-action-bar__end">
        {@render end()}
      </div>
    {/if}
  {/snippet}
</XSheet>

<style lang="scss" src="./_m-action-bar.scss"></style>
