// src/atoms/x-nav-drawer/x-nav-drawer.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue';
import type { XNavDrawerProps, XNavDrawerEmits } from './types';

defineOptions({
  name: 'XNavDrawer',
  inheritAttrs: false,
});

const props = withDefaults(defineProps<XNavDrawerProps>(), {
  modelValue: true,
  location: 'start',
  rail: false,
  temporary: false,
  permanent: false,
  width: 256,
  floating: false,
});

const emit = defineEmits<XNavDrawerEmits>();
const attrs = useAttrs();

const isOpen = computed({
  get: () => props.modelValue,
  set: (value: boolean) => emit('update:modelValue', value),
});
</script>

<template>
  <v-navigation-drawer
    v-model="isOpen"
    v-bind="attrs"
    :location="props.location"
    :rail="props.rail"
    :temporary="props.temporary"
    :permanent="props.permanent"
    :width="props.width"
    :floating="props.floating"
    class="x-nav-drawer"
  >
    <template v-if="$slots.prepend" #prepend>
      <slot name="prepend" />
    </template>
    <slot />
    <template v-if="$slots.append" #append>
      <slot name="append" />
    </template>
  </v-navigation-drawer>
</template>

// src/atoms/x-nav-drawer/x-nav-drawer.tsx
import React from 'react';
import type { XNavDrawerProps } from './types';
import { computeNavDrawerClasses, computeNavDrawerVars, hasDrawerScrim } from './x-nav-drawer.controller';

export interface ReactNavDrawerProps extends XNavDrawerProps {
  className?: string;
  onUpdateModelValue?: (value: boolean) => void;
  prepend?: React.ReactNode;
  append?: React.ReactNode;
  children?: React.ReactNode;
}

export const XNavDrawerReact: React.FC<ReactNavDrawerProps> = ({
  modelValue = true,
  location = 'start',
  rail = false,
  temporary = false,
  permanent = false,
  width = 256,
  floating = false,
  className = '',
  onUpdateModelValue = undefined,
  prepend = null,
  append = null,
  children = null,
}) => {
  const state = { modelValue, location, rail, temporary, permanent, width, floating };
  const resolvedClassNames = computeNavDrawerClasses(state, `x-nav-drawer--native ${className}`.trim()).join(' ');
  const drawerVars = computeNavDrawerVars(state) as React.CSSProperties;

  return (
    <>
      {hasDrawerScrim(state) ? (
        <div className="x-nav-drawer__scrim" role="presentation" onClick={() => onUpdateModelValue?.(false)} />
      ) : null}
      <nav className={resolvedClassNames} style={drawerVars}>
        {prepend}
        <div className="x-nav-drawer__content">{children}</div>
        {append}
      </nav>
    </>
  );
};

export default XNavDrawerReact;
