// src/atoms/x-chip/x-chip.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue';
import type { XChipProps, XChipEmits, XChipVariant } from './types';

defineOptions({
  name: 'XChip',
  inheritAttrs: false,
});

const props = withDefaults(defineProps<XChipProps>(), {
  variant: 'glass',
  color: undefined,
  size: 'default',
  closable: false,
  disabled: false,
  filter: false,
});

const emit = defineEmits<XChipEmits>();
const attrs = useAttrs();

const isGlassVariant = computed(() => props.variant === 'glass');

const computedVuetifyVariant = computed(() => {
  if (isGlassVariant.value) {
    return 'flat';
  }
  return props.variant as Exclude<XChipVariant, 'glass'>;
});

const handleClose = () => {
  emit('click:close');
};
</script>

<template>
  <v-chip
    v-bind="attrs"
    :variant="computedVuetifyVariant"
    :color="props.color"
    :size="props.size"
    :closable="props.closable"
    :disabled="props.disabled"
    :filter="props.filter"
    :class="['x-chip', { 'x-chip--glass': isGlassVariant }]"
    @click:close="handleClose"
  >
    <template v-if="$slots.prepend" #prepend="scope">
      <slot name="prepend" v-bind="(scope as any) || {}" />
    </template>
    <template v-if="$slots.close" #close="scope">
      <slot name="close" v-bind="(scope as any) || {}" />
    </template>
    <template #default="scope">
      <slot v-bind="(scope as any) || {}" />
    </template>
    <template v-if="$slots.append" #append="scope">
      <slot name="append" v-bind="scope || {}" />
    </template>
  </v-chip>
</template>

<style lang="scss" src="./_x-chip.scss"></style>

// src/atoms/x-chip/x-chip.svelte
<script lang="ts">
import type { Snippet } from 'svelte';
import type { XChipProps, XChipEmits } from './types';
import { computeChipClasses } from './x-chip.controller';

interface SvelteChipProps extends XChipProps {
  class?: string;
  onclick?: (e: MouseEvent) => void;
  onclose?: () => void;
  children?: Snippet;
  prepend?: Snippet;
}

let {
  variant = 'glass',
  color = undefined,
  size = 'default',
  closable = false,
  disabled = false,
  filter = false,
  class: className = '',
  onclick,
  onclose,
  children,
  prepend,
}: SvelteChipProps = $props();

const chipClasses = $derived(
  computeChipClasses({ variant, color, size, closable, disabled, filter }, className).join(' ')
);
</script>

<div class={chipClasses} {onclick} role="status">
  {#if prepend}
    <span class="x-chip__prepend">
      {@render prepend()}
    </span>
  {/if}

  {#if children}
    <span class="x-chip__content">
      {@render children()}
    </span>
  {/if}

  {#if closable}
    <button
      type="button"
      class="x-chip__close"
      onclick={(e) => {
        e.stopPropagation();
        onclose?.();
      }}
      aria-label="Close chip"
    >
      &times;
    </button>
  {/if}
</div>

<style lang="scss" src="./_x-chip.scss"></style>
