// src/atoms/x-chip/x-chip.svelte
<script lang="ts">
import type { Snippet } from 'svelte';
import type { XChipProps, XChipEmits } from './types';
import { computeChipClasses } from './x-chip.controller';

interface SvelteChipProps extends XChipProps {
  class?: string;
  onclick?: (e: MouseEvent) => void;
  onclose?: () => void;
  children?: Snippet;
  prepend?: Snippet;
}

let {
  variant = undefined,
  color = undefined,
  size = 'default',
  closable = false,
  disabled = false,
  filter = false,
  class: className = '',
  onclick,
  onclose,
  children,
  prepend,
}: SvelteChipProps = $props();

const chipClasses = $derived(
  computeChipClasses({ variant, color, size, closable, disabled, filter }, className).join(' ')
);
</script>

<div class={chipClasses} {onclick} role="status">
  {#if prepend}
    <span class="x-chip__prepend">
      {@render prepend()}
    </span>
  {/if}

  {#if children}
    <span class="x-chip__content">
      {@render children()}
    </span>
  {/if}

  {#if closable}
    <button
      type="button"
      class="x-chip__close"
      onclick={(e) => {
        e.stopPropagation();
        onclose?.();
      }}
      aria-label="Close chip"
    >
      &times;
    </button>
  {/if}
</div>

// src/atoms/x-chip/x-chip.tsx
import React from 'react';
import type { XChipProps } from './types';
import { computeChipClasses } from './x-chip.controller';

export interface ReactChipProps extends XChipProps {
  className?: string;
  onClick?: (e: React.MouseEvent<HTMLDivElement>) => void;
  onClose?: () => void;
  children?: React.ReactNode;
  prepend?: React.ReactNode;
}

export const XChipReact: React.FC<ReactChipProps> = ({
  variant = undefined,
  color = undefined,
  size = 'default',
  closable = false,
  disabled = false,
  filter = false,
  className = '',
  onClick = undefined,
  onClose = undefined,
  children = null,
  prepend = null,
}) => {
  const resolvedClassNames = computeChipClasses(
    { variant, color, size, closable, disabled, filter },
    className
  ).join(' ');

  const handleCloseClick = (e: React.MouseEvent<HTMLButtonElement>) => {
    e.stopPropagation();
    onClose?.();
  };

  return (
    <div className={resolvedClassNames} onClick={onClick} role="status">
      {prepend ? <span className="x-chip__prepend">{prepend}</span> : null}
      {children ? <span className="x-chip__content">{children}</span> : null}
      {closable ? (
        <button
          type="button"
          className="x-chip__close"
          onClick={handleCloseClick}
          aria-label="Close chip"
        >
          &times;
        </button>
      ) : null}
    </div>
  );
};

export default XChipReact;
