// src/atoms/x-card/x-card.svelte
<script lang="ts">
import type { Snippet } from 'svelte';
import type { XCardProps } from './types';
import { computeCardClasses } from './x-card.controller';

interface SvelteCardProps extends XCardProps {
  class?: string;
  children?: Snippet;
  title?: Snippet;
  actions?: Snippet;
}

let {
  variant = undefined,
  color = undefined,
  loading = false,
  disabled = false,
  hover = false,
  class: className = '',
  children,
  title,
  actions,
}: SvelteCardProps = $props();

const cardClasses = $derived(
  computeCardClasses({ variant, color, loading, disabled, hover }, className).join(' ')
);
</script>

<div class={cardClasses}>
  {#if title}
    <div class="x-card__title">
      {@render title()}
    </div>
  {/if}

  {#if children}
    <div class="x-card__content">
      {@render children()}
    </div>
  {/if}

  {#if actions}
    <div class="x-card__actions">
      {@render actions()}
    </div>
  {/if}
</div>

// src/atoms/x-card/x-card.tsx
import React from 'react';
import type { XCardProps } from './types';
import { computeCardClasses } from './x-card.controller';

export interface ReactCardProps extends XCardProps {
  className?: string;
  children?: React.ReactNode;
  title?: React.ReactNode;
  actions?: React.ReactNode;
}

export const XCardReact: React.FC<ReactCardProps> = ({
  variant = undefined,
  color = undefined,
  loading = false,
  disabled = false,
  hover = false,
  className = '',
  children = null,
  title = null,
  actions = null,
}) => {
  const resolvedClassNames = computeCardClasses(
    { variant, color, loading, disabled, hover },
    className
  ).join(' ');

  return (
    <div className={resolvedClassNames}>
      {title ? <div className="x-card__title">{title}</div> : null}
      {children ? <div className="x-card__content">{children}</div> : null}
      {actions ? <div className="x-card__actions">{actions}</div> : null}
    </div>
  );
};

export default XCardReact;
