// src/molecules/m-tabs-nav/m-tabs-nav.svelte
<script lang="ts">
import type { MTabsNavProps, NavTabItem } from './types';
import { computeTabsNavClasses } from './m-tabs-nav.controller';

interface SvelteTabsNavProps extends MTabsNavProps {
  class?: string;
  ontabchange?: (tabId: string) => void;
}

let {
  tabs,
  modelValue = $bindable(tabs[0] ? tabs[0].id : ''),
  grow = false,
  align = 'start',
  class: className = '',
  ontabchange,
}: SvelteTabsNavProps = $props();

const tabsClasses = $derived(
  computeTabsNavClasses({ tabs, grow, align }, className).join(' ')
);

const selectTab = (tab: NavTabItem) => {
  if (tab.disabled) return;
  modelValue = tab.id;
  ontabchange?.(tab.id);
};
</script>

<nav class={tabsClasses} role="tablist">
  {#each tabs as tab (tab.id)}
    <button
      type="button"
      role="tab"
      aria-selected={modelValue === tab.id}
      disabled={tab.disabled}
      class={['m-tabs-nav__item', modelValue === tab.id ? 'm-tabs-nav__item--active' : ''].join(' ')}
      onclick={() => selectTab(tab)}
    >
      {#if tab.icon}
        <span class="m-tabs-nav__icon">{tab.icon}</span>
      {/if}
      <span>{tab.label}</span>
      {#if tab.badge}
        <span class="m-tabs-nav__badge">{tab.badge}</span>
      {/if}
    </button>
  {/each}
</nav>

<style lang="scss" src="./_m-tabs-nav.scss"></style>

// src/molecules/m-tabs-nav/m-tabs-nav.tsx
import React from 'react';
import type { MTabsNavProps, NavTabItem } from './types';
import { computeTabsNavClasses } from './m-tabs-nav.controller';

export interface ReactTabsNavProps extends MTabsNavProps {
  className?: string;
  onTabChange?: (tabId: string) => void;
}

export const MTabsNavReact: React.FC<ReactTabsNavProps> = ({
  tabs,
  modelValue = undefined,
  grow = false,
  align = 'start',
  className = '',
  onTabChange = undefined,
}) => {
  const currentTab = modelValue || (tabs[0] ? tabs[0].id : '');
  const resolvedClassNames = computeTabsNavClasses(
    { tabs, grow, align },
    className
  ).join(' ');

  const handleSelect = (tab: NavTabItem) => {
    if (tab.disabled) return;
    onTabChange?.(tab.id);
  };

  return (
    <nav className={resolvedClassNames} role="tablist">
      {tabs.map((tab) => {
        const isActive = currentTab === tab.id;
        return (
          <button
            key={tab.id}
            type="button"
            role="tab"
            aria-selected={isActive}
            disabled={tab.disabled}
            className={`m-tabs-nav__item ${
              isActive ? 'm-tabs-nav__item--active' : ''
            }`}
            onClick={() => handleSelect(tab)}
          >
            {tab.icon ? (
              <span className="m-tabs-nav__icon">{tab.icon}</span>
            ) : null}
            <span>{tab.label}</span>
            {tab.badge ? (
              <span className="m-tabs-nav__badge">{tab.badge}</span>
            ) : null}
          </button>
        );
      })}
    </nav>
  );
};

export default MTabsNavReact;
