// src/atoms/x-divider/x-divider.tsx
import React from 'react';
import type { XDividerProps } from './types';
import { computeDividerClasses } from './x-divider.controller';

export interface ReactDividerProps extends XDividerProps {
  className?: string;
}

export const XDividerReact: React.FC<ReactDividerProps> = ({
  vertical = false,
  inset = false,
  className = '',
}) => {
  const resolvedClassNames = computeDividerClasses(
    { vertical, inset },
    className
  ).join(' ');

  return (
    <hr
      className={resolvedClassNames}
      aria-orientation={vertical ? 'vertical' : 'horizontal'}
    />
  );
};

export default XDividerReact;

// src/atoms/x-divider/x-divider.svelte
<script lang="ts">
import type { XDividerProps } from './types';
import { computeDividerClasses } from './x-divider.controller';

interface SvelteDividerProps extends XDividerProps {
  class?: string;
}

let {
  vertical = false,
  inset = false,
  class: className = '',
}: SvelteDividerProps = $props();

const dividerClasses = $derived(
  computeDividerClasses({ vertical, inset }, className).join(' ')
);
</script>

<hr class={dividerClasses} aria-orientation={vertical ? 'vertical' : 'horizontal'} />
