// src/molecules/m-kpi-tile/m-kpi-tile.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { MKpiTileProps } from './types';
import { resolveTrendClass, resolveTrendSymbol } from './m-kpi-tile.controller';
import XCard from '../../atoms/x-card/x-card.vue';

defineOptions({
  name: 'MKpiTile',
});

const props = withDefaults(defineProps<MKpiTileProps>(), {
  subtext: undefined,
  trend: undefined,
  trendValue: undefined,
  icon: undefined,
});

const trendClass = computed(() => resolveTrendClass(props.trend));
const trendSymbol = computed(() => resolveTrendSymbol(props.trend));
const hasTrend = computed(() => Boolean(props.trend && props.trendValue));
</script>

<template>
  <XCard variant="glass" hover>
    <div class="m-kpi-tile">
      <div class="m-kpi-tile__header">
        <span class="m-kpi-tile__label">{{ props.label }}</span>
        <slot name="icon">
          <span v-if="props.icon" class="m-kpi-tile__icon">{{ props.icon }}</span>
        </slot>
      </div>

      <div class="m-kpi-tile__value">
        {{ props.value }}
      </div>

      <div v-if="props.subtext || hasTrend" class="m-kpi-tile__footer">
        <span v-if="hasTrend" :class="['m-kpi-tile__trend', trendClass]">
          {{ trendSymbol }}{{ props.trendValue }}
        </span>
        <span v-if="props.subtext" class="m-kpi-tile__subtext">
          {{ props.subtext }}
        </span>
      </div>
    </div>
  </XCard>
</template>

<style lang="scss" src="./_m-kpi-tile.scss"></style>

// src/molecules/m-kpi-tile/m-kpi-tile.tsx
import React from 'react';
import type { MKpiTileProps } from './types';
import { resolveTrendClass, resolveTrendSymbol } from './m-kpi-tile.controller';
import XCardReact from '../../atoms/x-card/x-card';

export interface ReactKpiTileProps extends MKpiTileProps {
  iconElement?: React.ReactNode;
}

export const MKpiTileReact: React.FC<ReactKpiTileProps> = ({
  label,
  value,
  subtext = undefined,
  trend = undefined,
  trendValue = undefined,
  icon = undefined,
  iconElement = null,
}) => {
  const trendClass = resolveTrendClass(trend);
  const trendSymbol = resolveTrendSymbol(trend);
  const hasTrend = Boolean(trend && trendValue);

  return (
    <XCardReact variant="glass" hover={true}>
      <div className="m-kpi-tile">
        <div className="m-kpi-tile__header">
          <span className="m-kpi-tile__label">{label}</span>
          {iconElement ? (
            iconElement
          ) : icon ? (
            <span className="m-kpi-tile__icon">{icon}</span>
          ) : null}
        </div>

        <div className="m-kpi-tile__value">{value}</div>

        {subtext || hasTrend ? (
          <div className="m-kpi-tile__footer">
            {hasTrend ? (
              <span className={`m-kpi-tile__trend ${trendClass}`}>
                {trendSymbol}
                {trendValue}
              </span>
            ) : null}
            {subtext ? (
              <span className="m-kpi-tile__subtext">{subtext}</span>
            ) : null}
          </div>
        ) : null}
      </div>
    </XCardReact>
  );
};

export default MKpiTileReact;
