// src/molecules/m-kpi-tile/m-kpi-tile.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { MKpiTileProps } from './types';
import { resolveTrendClass, resolveTrendSymbol } from './m-kpi-tile.controller';
import XCard from '../../atoms/x-card/x-card.vue';

defineOptions({
  name: 'MKpiTile',
});

const props = withDefaults(defineProps<MKpiTileProps>(), {
  subtext: undefined,
  trend: undefined,
  trendValue: undefined,
  icon: undefined,
});

const trendClass = computed(() => resolveTrendClass(props.trend));
const trendSymbol = computed(() => resolveTrendSymbol(props.trend));
const hasTrend = computed(() => Boolean(props.trend && props.trendValue));
</script>

<template>
  <XCard variant="glass" hover>
    <div class="m-kpi-tile">
      <div class="m-kpi-tile__header">
        <span class="m-kpi-tile__label">{{ props.label }}</span>
        <slot name="icon">
          <span v-if="props.icon" class="m-kpi-tile__icon">{{ props.icon }}</span>
        </slot>
      </div>

      <div class="m-kpi-tile__value">
        {{ props.value }}
      </div>

      <div v-if="props.subtext || hasTrend" class="m-kpi-tile__footer">
        <span v-if="hasTrend" :class="['m-kpi-tile__trend', trendClass]">
          {{ trendSymbol }}{{ props.trendValue }}
        </span>
        <span v-if="props.subtext" class="m-kpi-tile__subtext">
          {{ props.subtext }}
        </span>
      </div>
    </div>
  </XCard>
</template>

<style lang="scss" src="./_m-kpi-tile.scss"></style>

// src/molecules/m-kpi-tile/m-kpi-tile.svelte
<script lang="ts">
import type { Snippet } from 'svelte';
import type { MKpiTileProps } from './types';
import { resolveTrendClass, resolveTrendSymbol } from './m-kpi-tile.controller';
import XCard from '../../atoms/x-card/x-card.svelte';

interface SvelteKpiTileProps extends MKpiTileProps {
  iconSnippet?: Snippet;
}

let {
  label,
  value,
  subtext = undefined,
  trend = undefined,
  trendValue = undefined,
  icon = undefined,
  iconSnippet,
}: SvelteKpiTileProps = $props();

const trendClass = $derived(resolveTrendClass(trend));
const trendSymbol = $derived(resolveTrendSymbol(trend));
const hasTrend = $derived(Boolean(trend && trendValue));
</script>

<XCard variant="glass" hover={true}>
  {#snippet children()}
    <div class="m-kpi-tile">
      <div class="m-kpi-tile__header">
        <span class="m-kpi-tile__label">{label}</span>
        {#if iconSnippet}
          {@render iconSnippet()}
        {:else if icon}
          <span class="m-kpi-tile__icon">{icon}</span>
        {/if}
      </div>

      <div class="m-kpi-tile__value">
        {value}
      </div>

      {#if subtext || hasTrend}
        <div class="m-kpi-tile__footer">
          {#if hasTrend}
            <span class={['m-kpi-tile__trend', trendClass].join(' ')}>
              {trendSymbol}{trendValue}
            </span>
          {/if}
          {#if subtext}
            <span class="m-kpi-tile__subtext">{subtext}</span>
          {/if}
        </div>
      {/if}
    </div>
  {/snippet}
</XCard>

<style lang="scss" src="./_m-kpi-tile.scss"></style>
