// src/atoms/x-sheet/x-sheet.svelte
<script lang="ts">
import type { Snippet } from 'svelte';
import type { XSheetProps } from './types';
import { computeSheetClasses } from './x-sheet.controller';

interface SvelteSheetProps extends XSheetProps {
  class?: string;
  children?: Snippet;
}

let {
  color = undefined,
  elevation = undefined,
  rounded = undefined,
  border = undefined,
  transparent = false,
  class: className = '',
  children,
}: SvelteSheetProps = $props();

const sheetClasses = $derived(
  computeSheetClasses({ transparent, color, elevation, rounded, border }, className).join(' ')
);
</script>

<div class={sheetClasses}>
  {#if children}
    {@render children()}
  {/if}
</div>

// src/atoms/x-sheet/x-sheet.tsx
import React from 'react';
import type { XSheetProps } from './types';
import { computeSheetClasses } from './x-sheet.controller';

export interface ReactSheetProps extends XSheetProps {
  className?: string;
  children?: React.ReactNode;
}

export const XSheetReact: React.FC<ReactSheetProps> = ({
  color = undefined,
  elevation = undefined,
  rounded = undefined,
  border = undefined,
  transparent = false,
  className = '',
  children = null,
}) => {
  const resolvedClassNames = computeSheetClasses(
    { transparent, color, elevation, rounded, border },
    className
  ).join(' ');

  return <div className={resolvedClassNames}>{children}</div>;
};

export default XSheetReact;
