// src/atoms/x-sheet/x-sheet.svelte
<script lang="ts">
import type { Snippet } from 'svelte';
import type { XSheetProps } from './types';
import { computeSheetClasses } from './x-sheet.controller';

interface SvelteSheetProps extends XSheetProps {
  class?: string;
  children?: Snippet;
}

let {
  color = undefined,
  elevation = undefined,
  rounded = undefined,
  border = undefined,
  transparent = false,
  class: className = '',
  children,
}: SvelteSheetProps = $props();

const sheetClasses = $derived(
  computeSheetClasses({ transparent, color, elevation, rounded, border }, className).join(' ')
);
</script>

<div class={sheetClasses}>
  {#if children}
    {@render children()}
  {/if}
</div>

<style lang="scss" src="./_x-sheet.scss"></style>

// src/atoms/x-sheet/x-sheet.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue';
import type { XSheetProps } from './types';

defineOptions({
  name: 'XSheet',
  inheritAttrs: false,
});

const props = withDefaults(defineProps<XSheetProps>(), {
  color: undefined,
  elevation: undefined,
  rounded: undefined,
  border: undefined,
  transparent: false,
});

const attrs = useAttrs();

const resolvedColor = computed(() => {
  if (props.transparent) {
    return 'transparent';
  }
  return props.color;
});
</script>

<template>
  <v-sheet
    v-bind="attrs"
    :color="resolvedColor"
    :elevation="props.elevation"
    :rounded="props.rounded"
    :border="props.border"
    :class="['x-sheet', { 'x-sheet--transparent': props.transparent }]"
  >
    <slot />
  </v-sheet>
</template>

<style lang="scss" src="./_x-sheet.scss"></style>
